import {SUPPORTED_RAW_COMMANDS} from "./aliases";

export type StemScriptCommandEffect =
    | "builtin"
    | "read-only"
    | "creator"
    | "setter"
    | "destructive"
    | "asset-query"
    | "asset-import"
    | "external";

export type StemScriptVerificationLevel =
    | "read-only"
    | "full-set-get"
    | "partial-set-get"
    | "check-only"
    | "intentional-skip";

export interface StemScriptCommandContract {
    command: string;
    effect: StemScriptCommandEffect;
    area: string;
    verification: StemScriptVerificationLevel;
    sample: string;
    skipReason?: string;
}

export const STEMSCRIPT_COMMAND_CONTRACTS: StemScriptCommandContract[] = [
    {
        command: "create_primitive",
        effect: "creator",
        area: "object",
        verification: "full-set-get",
        sample: "create_primitive type=box name=ContractBox position=1,2,3 color=#ff0000",
    },
    {
        command: "create_group",
        effect: "creator",
        area: "object",
        verification: "full-set-get",
        sample: "create_group name=ContractGroup position=0,1,0",
    },
    {
        command: "clone_object",
        effect: "creator",
        area: "object",
        verification: "intentional-skip",
        sample: "clone_object target=ContractBox position=2,0,0",
        skipReason: "Clone result names are generated by editor clone semantics and need a dedicated negative/positive scene assertion.",
    },
    {
        command: "delete_object",
        effect: "destructive",
        area: "object",
        verification: "intentional-skip",
        sample: "delete_object target=ContractBox",
        skipReason: "Deletion is verified by absence, not by an equivalent successful getter probe.",
    },
    {
        command: "move_object",
        effect: "setter",
        area: "object",
        verification: "full-set-get",
        sample: "move_object target=ContractBox parent=ContractGroup",
    },
    {
        command: "modify_object",
        effect: "setter",
        area: "object",
        verification: "full-set-get",
        sample: "modify_object target=ContractBox position=3,2,1 color=#00ff00",
    },
    {
        command: "get_scene_objects",
        effect: "read-only",
        area: "object",
        verification: "read-only",
        sample: "get_scene_objects filter=*",
    },
    {
        command: "get_object",
        effect: "read-only",
        area: "object",
        verification: "read-only",
        sample: "get_object target=ContractBox",
    },
    {
        command: "get_object_settings",
        effect: "read-only",
        area: "object",
        verification: "read-only",
        sample: "get_object_settings target=ContractBox kind=box",
    },
    {
        command: "get_material_settings",
        effect: "read-only",
        area: "material",
        verification: "read-only",
        sample: "get_material_settings target=ContractBox",
    },
    {
        command: "get_behavior_settings",
        effect: "read-only",
        area: "behavior",
        verification: "read-only",
        sample: "get_behavior_settings target=ContractBox behaviorId=contract.behavior",
    },
    {
        command: "get_selected_object",
        effect: "read-only",
        area: "object",
        verification: "read-only",
        sample: "get_selected_object",
    },
    {
        command: "get_player",
        effect: "read-only",
        area: "object",
        verification: "read-only",
        sample: "get_player",
    },
    {
        command: "set_material",
        effect: "setter",
        area: "material",
        verification: "full-set-get",
        sample: "set_material target=ContractBox color=#336699 opacity=0.5 metalness=0.2 roughness=0.7",
    },
    {
        command: "set_texture",
        effect: "setter",
        area: "material",
        verification: "partial-set-get",
        sample: "set_texture target=ContractBox imageAsset=ContractTexture textureType=map",
    },
    {
        command: "set_external_texture",
        effect: "setter",
        area: "material",
        verification: "partial-set-get",
        sample: "set_external_texture target=ContractBox assetId=asset-texture assetType=textures name=ContractTexture provider=local",
    },
    {
        command: "list_behaviors",
        effect: "read-only",
        area: "behavior",
        verification: "read-only",
        sample: "list_behaviors filter=*",
    },
    {
        command: "get_behavior",
        effect: "read-only",
        area: "behavior",
        verification: "read-only",
        sample: "get_behavior behaviorId=contract.behavior",
    },
    {
        command: "add_behavior",
        effect: "asset-import",
        area: "behavior",
        verification: "intentional-skip",
        sample: "add_behavior name=ContractBehavior code=ContractCode",
        skipReason: "Behavior asset creation is persisted through editor asset APIs and needs a mocked asset-registry contract.",
    },
    {
        command: "update_behavior",
        effect: "asset-import",
        area: "behavior",
        verification: "intentional-skip",
        sample: "update_behavior behaviorId=contract.behavior code=ContractCode",
        skipReason: "Behavior asset revision updates are persisted through asset APIs and are covered by behavior handler tests.",
    },
    {
        command: "attach_behavior",
        effect: "setter",
        area: "behavior",
        verification: "full-set-get",
        sample: "attach_behavior target=ContractBox behaviorId=contract.behavior config={speed:3}",
    },
    {
        command: "add_navmesh",
        effect: "setter",
        area: "behavior",
        verification: "partial-set-get",
        sample: "add_navmesh target=DefaultScene autoGenerate=true agentRadius=0.4",
    },
    {
        command: "rebuild_navmesh",
        effect: "setter",
        area: "behavior",
        verification: "intentional-skip",
        sample: "rebuild_navmesh target=DefaultScene",
        skipReason: "Rebuild emits an editor change event but does not write a deterministic setting value.",
    },
    {
        command: "add_navmesh_connection",
        effect: "setter",
        area: "behavior",
        verification: "intentional-skip",
        sample: "add_navmesh_connection source=ContractBox target=ContractGroup bidirectional=true",
        skipReason: "Connection data references target UUIDs and needs a scene fixture with stable source/target objects.",
    },
    {
        command: "add_waypoint_path",
        effect: "creator",
        area: "behavior",
        verification: "intentional-skip",
        sample: "add_waypoint_path name=ContractPath loop=true",
        skipReason: "Waypoint paths are object creations with waypoint-specific userData and need dedicated object assertions.",
    },
    {
        command: "add_waypoint",
        effect: "creator",
        area: "behavior",
        verification: "intentional-skip",
        sample: "add_waypoint path=ContractPath position=1,0,2 order=1",
        skipReason: "Waypoint markers are generated child objects and need dedicated path membership assertions.",
    },
    {
        command: "detach_behavior",
        effect: "destructive",
        area: "behavior",
        verification: "partial-set-get",
        sample: "detach_behavior target=ContractBox behaviorId=contract.behavior",
    },
    {
        command: "remove_behavior",
        effect: "destructive",
        area: "behavior",
        verification: "intentional-skip",
        sample: "remove_behavior behaviorId=contract.behavior",
        skipReason: "Behavior asset removal spans scene instances, asset resolution, registries, and persistence.",
    },
    {
        command: "set_behavior_config",
        effect: "setter",
        area: "behavior",
        verification: "full-set-get",
        sample: "set_behavior_config target=ContractBox behaviorId=contract.behavior attributesData={speed:5} enabled=false",
    },
    {
        command: "enable_physics",
        effect: "setter",
        area: "physics",
        verification: "full-set-get",
        sample: "enable_physics target=ContractBox shape=capsule ctype=kinematic",
    },
    {
        command: "disable_physics",
        effect: "setter",
        area: "physics",
        verification: "full-set-get",
        sample: "disable_physics target=ContractBox",
    },
    {
        command: "set_physics",
        effect: "setter",
        area: "physics",
        verification: "full-set-get",
        sample: "set_physics target=ContractBox config={enabled:true,shape:\"box\",mass:2,friction:0.4,restitution:0.1,ctype:\"dynamic\"}",
    },
    {
        command: "get_physics_settings",
        effect: "read-only",
        area: "physics",
        verification: "read-only",
        sample: "get_physics_settings target=ContractBox",
    },
    {
        command: "set_physics_engine",
        effect: "setter",
        area: "physics",
        verification: "full-set-get",
        sample: "set_physics_engine type=ammo gravity=-9.81",
    },
    {
        command: "set_scene_compartments",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_scene_compartments enabled=true",
    },
    {
        command: "set_scene_thumbnail",
        effect: "setter",
        area: "scene",
        verification: "intentional-skip",
        skipReason: "thumbnail is a blob upload with no deterministic getter probe",
        sample: "set_scene_thumbnail name=DefaultThumbnail",
    },
    {
        command: "get_light_settings",
        effect: "read-only",
        area: "light",
        verification: "read-only",
        sample: "get_light_settings target=Directional",
    },
    {
        command: "generate_3d_model",
        effect: "external",
        area: "asset",
        verification: "intentional-skip",
        sample: "generate_3d_model prompt=tree name=ContractTree",
        skipReason: "Model generation is asynchronous and provider-backed.",
    },
    {
        command: "search_local_assets",
        effect: "asset-query",
        area: "asset",
        verification: "read-only",
        sample: "search_local_assets phrases=[tree] type=model",
    },
    {
        command: "get_library_asset",
        effect: "asset-query",
        area: "asset",
        verification: "read-only",
        sample: "get_library_asset assetId=asset-model",
    },
    {
        command: "search_external_assets",
        effect: "asset-query",
        area: "asset",
        verification: "read-only",
        sample: "search_external_assets phrases=[tree] type=model",
    },
    {
        command: "add_model_to_scene",
        effect: "asset-import",
        area: "asset",
        verification: "partial-set-get",
        sample: "add_model_to_scene id=asset-model name=ContractModel provider=local downloadUrl=/model.glb",
    },
    {
        command: "add_vfx",
        effect: "creator",
        area: "vfx",
        verification: "partial-set-get",
        sample: "add_vfx name=ContractSmoke position=0,1,0 config={autoStart:true}",
    },
    {
        command: "modify_vfx",
        effect: "setter",
        area: "vfx",
        verification: "partial-set-get",
        sample: "modify_vfx target=ContractSmoke position=1,2,3",
    },
    {
        command: "delete_vfx",
        effect: "destructive",
        area: "vfx",
        verification: "intentional-skip",
        sample: "delete_vfx target=ContractSmoke",
        skipReason: "VFX deletion is verified by absence, not by an equivalent successful getter probe.",
    },
    {
        command: "get_vfx",
        effect: "read-only",
        area: "vfx",
        verification: "read-only",
        sample: "get_vfx target=ContractSmoke",
    },
    {
        command: "add_vfx_behavior",
        effect: "setter",
        area: "vfx",
        verification: "intentional-skip",
        sample: "add_vfx_behavior target=ContractSmoke behaviorType=SizeOverLife config={}",
        skipReason: "VFX behavior serialization needs effect-specific assertions beyond the generic getter probe.",
    },
    {
        command: "remove_vfx_behavior",
        effect: "destructive",
        area: "vfx",
        verification: "intentional-skip",
        sample: "remove_vfx_behavior target=ContractSmoke behaviorIndex=0",
        skipReason: "VFX behavior removal needs effect-specific absence assertions.",
    },
    {
        command: "list_prefabs",
        effect: "asset-query",
        area: "prefab",
        verification: "read-only",
        sample: "list_prefabs filter=*",
    },
    {
        command: "get_prefab",
        effect: "asset-query",
        area: "prefab",
        verification: "read-only",
        sample: "get_prefab id=asset-prefab",
    },
    {
        command: "add_prefab_to_scene",
        effect: "asset-import",
        area: "prefab",
        verification: "partial-set-get",
        sample: "add_prefab_to_scene id=asset-prefab name=ContractPrefab",
    },
    {
        command: "create_prefab",
        effect: "asset-import",
        area: "prefab",
        verification: "intentional-skip",
        sample: "create_prefab target=ContractBox name=ContractPrefab",
        skipReason: "Prefab creation persists an asset and thumbnail derivative; handler tests should own that mocked boundary.",
    },
    {
        command: "set_scene_lighting",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_scene_lighting ambient={color:\"#ffffff\",intensity:0.5} shadows={enabled:true,mapType:\"PCFSoftShadowMap\"}",
    },
    {
        command: "set_scene_fog",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_scene_fog type=linear color=#aabbcc near=5 far=80",
    },
    {
        command: "set_scene_background",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_scene_background type=Color color=#112233",
    },
    {
        command: "set_tone_mapping",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_tone_mapping type=ACESFilmicToneMapping exposure=1.2",
    },
    {
        command: "set_post_processing",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_post_processing outline={enabled:true,edgeStrength:2} bloom={enabled:true,strength:0.4}",
    },
    {
        command: "set_camera_settings",
        effect: "setter",
        area: "camera",
        verification: "full-set-get",
        sample: "set_camera_settings target=DefaultCamera cameraType=NONE fov=60 near=0.01 far=500",
    },
    {
        command: "get_camera_settings",
        effect: "read-only",
        area: "camera",
        verification: "read-only",
        sample: "get_camera_settings target=DefaultCamera",
    },
    {
        command: "set_game_settings",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_game_settings isGame=true lives=3 maxScore=10 timer=60 useAvatar=true isMultiplayer=false showHUD=true",
    },
    {
        command: "set_project_title",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_project_title title=ContractProject",
    },
    {
        command: "set_rendering_settings",
        effect: "setter",
        area: "scene",
        verification: "full-set-get",
        sample: "set_rendering_settings useShadows=true useInstancing=true shadowMapType=PCFSoftShadowMap usePhysicsWorker=true",
    },
    {
        command: "get_editor_settings",
        effect: "read-only",
        area: "scene",
        verification: "read-only",
        sample: "get_editor_settings category=all",
    },
    {
        command: "get_scene_setting",
        effect: "read-only",
        area: "scene",
        verification: "read-only",
        sample: "get_scene_setting category=lighting",
    },
    {
        command: "set_light_properties",
        effect: "setter",
        area: "light",
        verification: "full-set-get",
        sample: 'set_light_properties target="Directional Light" intensity=2 color=#ffeeaa castShadow=true shadowMapSize=1024',
    },
];

export const STEMSCRIPT_BUILTIN_CONTRACTS: StemScriptCommandContract[] = [
    {command: "help", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "help", skipReason: "Terminal UI command."},
    {command: "clear", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "clear", skipReason: "Terminal UI command."},
    {command: "history", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "history", skipReason: "Terminal UI command."},
    {command: "exit", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "exit", skipReason: "Terminal UI command."},
    {command: "exec", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "exec", skipReason: "Executes selected scripts."},
    {command: "save", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "save", skipReason: "Persists current script buffer."},
    {command: "import", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "import model name=ContractModel filepath=models/model.glb", skipReason: "File import is validated by import pipeline tests."},
    {command: "export", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "export scene", skipReason: "Export emits a bundle rather than a scene setting."},
    {command: "dump", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "dump scene", skipReason: "Dump emits a local bundle rather than a scene setting."},
    {command: "require", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "require proxy api http://localhost", skipReason: "Documents external proxy requirements."},
    {command: "check", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "check", skipReason: "Validation command; skipped to prevent recursion."},
    {command: "test", effect: "builtin", area: "terminal", verification: "intentional-skip", sample: "test", skipReason: "Executes and validates selected scripts."},
];

export const STEMSCRIPT_ALIAS_SAMPLES: Array<{input: string; command: string}> = [
    {input: "add box name=AliasBox", command: "create_primitive"},
    {input: "add sphere name=AliasSphere", command: "create_primitive"},
    {input: "add cylinder name=AliasCylinder", command: "create_primitive"},
    {input: "add cone name=AliasCone", command: "create_primitive"},
    {input: "add plane name=AliasPlane", command: "create_primitive"},
    {input: "add torus name=AliasTorus", command: "create_primitive"},
    {input: "add torusknot name=AliasTorusKnot", command: "create_primitive"},
    {input: "add triangle name=AliasTriangle", command: "create_primitive"},
    {input: "add capsule name=AliasCapsule", command: "create_primitive"},
    {input: "add icosahedron name=AliasIcosahedron", command: "create_primitive"},
    {input: "add octahedron name=AliasOctahedron", command: "create_primitive"},
    {input: "add dodecahedron name=AliasDodecahedron", command: "create_primitive"},
    {input: "add ring name=AliasRing", command: "create_primitive"},
];

export const STEMSCRIPT_COMMAND_CONTRACT_BY_NAME = new Map(
    STEMSCRIPT_COMMAND_CONTRACTS.map(contract => [contract.command, contract]),
);

export const STEMSCRIPT_BUILTIN_CONTRACT_BY_NAME = new Map(
    STEMSCRIPT_BUILTIN_CONTRACTS.map(contract => [contract.command, contract]),
);

export function getMissingRawCommandContracts(): string[] {
    return SUPPORTED_RAW_COMMANDS.filter(command => !STEMSCRIPT_COMMAND_CONTRACT_BY_NAME.has(command));
}

export function isMutationContract(contract: StemScriptCommandContract): boolean {
    return !["builtin", "read-only", "asset-query"].includes(contract.effect);
}
