export const PLAYGROUND_STEMSCRIPT_KNOWLEDGE = `
StemStudio playground knowledge base, distilled from stemstudio-importer docs:
- Work live in the browser editor. Build with primitives, groups, scene settings, materials, textures, physics, cameras, VFX, game settings, navmesh/waypoints, and behavior scripts. Avoid external search/generation for direct playground prompts.
- Scale: 1 unit = 1 meter. A human player is usually a capsule around size=0.5,1.8,0.5 at position=0,0.9,0. Floors can be boxes such as size=50,0.1,50 at position=0,-0.05,0. Platforms are often size=3,0.2,3. Trigger zones should be wider than the player, usually at least 1.5 m.
- Primitive dimensions: prefer size over scale for new geometry. For capsules and cylinders, size.x is diameter and size.y is height or length. For spheres, size.x is diameter. For boxes, size is width,height,depth.
- Object commands: add group name=Arena; add box|sphere|cylinder|cone|plane|torus|torusKnot|triangle|capsule|icosahedron|octahedron|dodecahedron|ring name=Object position=x,y,z size=x,y,z color=#rrggbb parent=Group; clone Target name=Copy position=x,y,z; delete Target; move Target parent=Group keepLocalSpace=true; update Target position=x,y,z rotation=x,y,z scale=x,y,z color=#rrggbb tag=Player.
- Object settings: use objectSettings={isBatchable:true,isStatic:true} for repeated or static level pieces when appropriate. Use update Target tag=Player or tag=Goal after creation; tags are an update operation. Use inspectionStemscript with get/list commands before risky edits: list objects, get Target, get settings Target, get material Target, get physics Target, get behavior Target behaviorId=<id>, get selected, get player, get camera DefaultCamera, get game settings, get scene settings.
- Asset/import inspection: use read-only scene asset commands to see imported resources before referencing them. Commands: list assets type=all|models|imports|files|behaviors|lambdas|packs|media filter=<text> limit=80; get asset assetId=<id-or-name>; list models; list imports; list files; list behavior packs; list lambda packs; get import <name>; get file <name>. Models are 3D model assets, imports are script import assets, files are generic data files, behavior/lambda packs are asset-backed registered packs, media includes image/audio/video, vfx maps to Quarks assets, and prefab/stem maps to Prefab assets. Use asset names, descriptions, tags, formats, and revision IDs from these results to choose reusable existing assets before generating replacement code.
- Physics: enable physics before detailed physics config. Use shape values box, sphere, capsule, convexHull, or concaveHull. Use concaveHull only for static terrain, tracks, or buildings. Use ctype Static, Dynamic, or Kinematic. Static level geometry should usually have mass 0; player-like bodies are usually Dynamic or Kinematic.
- Camera: configure "DefaultCamera". Use cameraType=THIRD_PERSON for 3D character or kart scenes, FIRST_PERSON for first-person scenes, TOP_DOWN for board or arena games, SIDE_SCROLLER for side-view platformers, and NONE when only projection settings are needed.
- Materials and atmosphere: use material Target color=#rrggbb roughness=0.5 metalness=0.1 opacity=1, texture Target textureUrl=<url>|imageAsset=<name> textureType=map, scene background, scene lighting, scene fog, scene tonemapping, scene postprocessing, light, render settings, and game settings to make primitives readable. Keep colors high-contrast enough to understand the play space.
- VFX: vfx add can rely on defaults. Use config.shape typed descriptors such as {type:"PointEmitter"}, {type:"SphereEmitter",radius:1.5}, or {type:"CircleEmitter",radius:0.75}. Generator values use typed objects such as {type:"ConstantValue",value:20} or {type:"IntervalValue",a:1,b:2}. Use worldSpace:true for trails that should detach from moving objects.
- VFX behaviors: use vfx behavior add Effect behaviorType=ColorOverLife config={mode:"gradient"} or vfx behavior remove Effect behaviorIndex=0. Use vfx modify Effect config={...} for particle system changes and vfx get Effect before modifying an existing system.
- Behavior registry: use the Available behavior registry JSON from the user prompt when present; it is the compact list of all currently registered behavior packs/configs. Use behavior list and behavior get behaviorId=<id> for inspection commands when you need full metadata or code, and use list behavior packs/get asset to inspect imported behavior assets. Prefer exact behavior IDs from the registry/catalog; do not invent behaviorId values when an existing pack fits. Use behavior add name="BehaviorName" description="Copilot generated for: <request>; purpose: <runtime role>; inspected/reused: <asset ids or behavior ids>" code="..." for new behavior scripts, behavior update behaviorId=<id> description="Copilot revised for: <request>; changed: <summary>" code="..." for revisions, and behavior remove behaviorId=<id> only when the user explicitly asks to remove custom behavior code.
- Behavior attachment: use behavior attach Target behaviorId=BehaviorName config={...}, behavior config Target behaviorId=BehaviorName attributesData={...} enabled=true, and behavior detach Target behaviorId=BehaviorName. When creating a playable experience, attach/configure the needed behavior components in the same script; do not stop after primitives. For trigger-style behavior config, attributesData/config can include if_condition, if_operator, and then_steps. variable_compare conditions read from erth.store keys.
- Built-in behavior catalog: character creates a controllable player (isDefault, walkSpeed, runSpeed, jumpHeight, health, autoForward); consumable creates pickups (pointAmount, healthAmount, speedAmount, jumpAmount, disposable, canReappear); trigger creates interactive/collision/timer logic (if_condition, if_operator, then_steps); tween moves/rotates/scales objects and is good for doors, lifts, animated hazards (startOnTrigger, move, rotate, scale, speed, loopMode); platform creates moving platforms (startOnTrigger, move, speed, loopMode); enemy creates basic hostile AI (enemyType, health, movementSpeed, attackDamage, attackDistance); projectile creates moving damaging objects (speed, gravity, lifetime, damage, radius); npc creates ambient roaming NPCs (movementType, movementSpeed, roamDistance, engageDistance); aiNpc creates conversational NPCs when provider/server support exists (npc_profile, voice_id, range, environment); follow makes an object follow another (followTargetUuid, distance, speed, rotate); jumppad launches characters (strength, enableAngle, angle); teleport moves players to a target (teleportTargetUuid); objectInteractions enables pickup/drop/push/pull (pickUp, drop, push, pull, interactionDistance); enableDisable toggles objects or behaviors (startOnTrigger, action, targetType, targetObject); visualEffect plays particle events (startOnTrigger, triggerEvents, customTriggerEvents); genericSound plays audio (startOnTrigger, audioAsset, positional, looping, autoPlay, volume); cinematicCamera, animation, dayNightCycle, touchControls, spawnpoint, navmesh, and navmesh-connection are also built-in IDs.
- Behavior recipes: playable character scenes usually need add capsule name=Player, update Player tag=Player, behavior attach Player behaviorId=character config={isDefault:true,walkSpeed:3,runSpeed:8,jumpHeight:1.2}, camera "DefaultCamera" cameraType=THIRD_PERSON defaultDistance=6, game settings isGame=true showHUD=true. Collectible goals use behavior attach Coin behaviorId=consumable config={pointAmount:1,disposable:true} plus game settings maxScore=<count>. Triggered doors/lifts use behavior attach Door behaviorId=tween config={startOnTrigger:true,move:{x:0,y:3,z:0},speed:1,loopMode:"Once"} and behavior attach TriggerZone behaviorId=trigger config={if_condition:[{conditionType:"player_touches"}],if_operator:"and",then_steps:[{thenType:"activate",delay:0}]}; if exact trigger target fields are uncertain, create a small custom controller behavior instead of emitting broken target references.
- Behavior code lifecycle: valid behavior methods include this.init = function(game) {}, this.update = function(deltaTime) {}, this.fixedUpdate = function(fixedDeltaTime) {}, this.dispose = function() {}, this.onEvent = function(msg,data) {}, this.onStart = function() {}, and this.onStop = function() {}. Prefer let/const, avoid remote dependencies, keep code short, and avoid hallucinated APIs. Use game/runtime APIs exposed by the editor; inspect existing behavior docs when available. Descriptions are searchable metadata, so generated or revised behavior code should always describe the gameplay purpose and any existing assets/packs it was matched against.
- Lambda API reference: imported lambda YAML/assets can use runtime lambdas APIs such as lambdas.getInstance, lambdas.getInstancesByType, lambdas.registerObject, lambdas.deregisterObject, and lambdas.getObjectLambdas. Lambda code should not use this.erth, this.target, or this.gameObject; lambdas process many objects through this.processObjects(...) and object arguments. The Available lambda registry JSON is the compact list of all currently registered lambda packs/configs. Use lambda list filter=<text>, lambda get lambdaId=<id> includeCode=true, list lambda packs, and get asset assetId=<lambda-asset> as read-only inspection commands when debugging existing lambda config, component bindings, scene instances, assets, or code. Direct playground chat can explain/import lambda assets but does not auto-open a file picker.
- Navmesh and waypoints: navmesh add target="Default Scene" autoGenerate=true agentHeight=1.8 agentRadius=0.45 debugVisualization=false; navmesh rebuild; navmesh connection add Start target=End bidirectional=false radius=0.75; waypoint path add name=PatrolPath loop=true; waypoint add path=PatrolPath position=x,y,z order=0 waitTime=1 arrivalRadius=0.5.
- Import API reference: terminal StemScript supports import model, behavior, lambda, vfx, image, audio/sound, video, prefab, script/import, and file. Syntax: import <type> <name> [filepath] ["comment"], import <type> name=<name> filepath=<path>, or import <type> name=<name> url=<url>. Examples: import model Kart kart.glb; import behavior NpcController behaviors/npc.yaml; import lambda PatrolBrain lambdas/patrol.yaml; import script name="math-helpers" filepath="imports/math-helpers.js"; import file name="level-data" filepath="data/level.json". Direct playground copilot should not emit import commands unless an import executor is available; instead inspect existing assets with list imports/list files/list models, provide exact import lines in the reply, and use primitives/behaviors for immediate edits.
- Genre recipes: a small platformer needs a Player capsule, Ground, 3 to 5 platforms, a collectible, a goal trigger, physics, and SIDE_SCROLLER or THIRD_PERSON camera. A racing sketch needs a kart body, ground or track blocks, 3 checkpoint triggers, start/finish markers, physics, and THIRD_PERSON camera. A top-down arena needs a player marker, boundaries, obstacles, pickups, and TOP_DOWN camera.
- Gameplay recipes: for an arcade loop, start with project title "<Short Game Name>" and game settings isGame=true showHUD=true, then create clear spawn, goal, hazards, collectibles, scoring variables, reset rules, camera, lights, and player feedback. Use behavior scripts for motion, scoring, health, timers, AI patrol, pickups, checkpoints, or win/lose logic when primitives alone are not enough.
- Performance: keep live plans compact. Prefer grouped pieces and repeated simple primitives over hundreds of unique meshes. Avoid huge command counts unless the user explicitly asks for a large build.
`.trim();
