export enum BehaviorAttributeType {
    Boolean = 'boolean',
    Number = 'number',
    Float = 'float',
    String = 'string',
    Vector3 = 'vector3',
    Vector2 = 'vector2',
    Separator = 'separator',
    Label = 'label',
    Enum = 'enum',
    Object = 'object',
    Children = 'children',
    Prefab = 'prefab',
    ModelAsset = 'modelAsset',
    Slider = 'slider',
    Image = 'image',
    ImageAsset = 'imageAsset',
    AudioAsset = 'audioAsset',
    VideoAsset = 'videoAsset',
    Array = 'array',
    Group = 'group',
    ObjectBehaviors = 'objectBehaviors',
    Video = 'video',
    Button = 'button',
    ModelPreview = 'modelPreview',
    Color = 'color',
    FileAsset = 'fileAsset',
}

export default BehaviorAttributeType;